ScaleWebTest/Controllers/ProtocolsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Diagnostics;
using System.Globalization;
using System.Web.Mvc;
using ScaleService;
using ScaleWebTest.Properties;

namespace ScaleWebTest.Controllers
{
    public class ProtocolsController : Controller
    {
        //
        // GET: /Protocols/

        public ActionResult Index()
        {
            string host = Session["hostName"] as string;
            if (host == null) return RedirectToAction("Index", "Home");

            try
            {
                Stopwatch queryTime = new Stopwatch();
                ScaleServiceClient client = new ScaleServiceClient(host);

              //  var httpCookie = Request.Cookies["Session"];
              //  if (httpCookie == null)
              //  {
              //    //no esta con dentro de la app
              //    TempData["central-error"] = "No se pudo acceder al servidor central.";
                  
              //    //ViewBag.QueryTime = "";
              //    return RedirectToAction("Index", "Home");
              //  }
              //if (!ValidateCok(httpCookie.Value.ToString(CultureInfo.InvariantCulture)))
              //{
              //  TempData["central-error"] = "No se pudo acceder al servidor central.";

              //  //ViewBag.QueryTime = "";
              //  return RedirectToAction("Index", "Home");
              //}
                IEnumerable<string> availableProtocols = client.GetAvailableProtocols();

                queryTime.Start();
               
                queryTime.Stop();
                ViewBag.QueryTime = queryTime.Elapsed.ToString();
                return View(availableProtocols);
            }
            catch (Exception)
            {
                TempData["error"] = "No se pudo conectar al computador de báscula (" + host + ") especificado.";
                return RedirectToAction("Index", "Home");
            }
            
        }
        private bool ValidateCok(string SesCode)
        {
          SqlConnection sqlConnection;
          if (Settings.Default.ExecutionEnvironment.ToLower() == "production")
            sqlConnection = new SqlConnection(Settings.Default.ProductionDbConnectionString);
          else
            sqlConnection = new SqlConnection(Settings.Default.DebugDbConnectionString);
          sqlConnection.Open();
          var SqlQuery = @"select * from adSessions where SesCode='" + SesCode + "'";
          SqlCommand sqlCommand = new SqlCommand(SqlQuery, sqlConnection);
          SqlDataReader sqlDataReader = sqlCommand.ExecuteReader(CommandBehavior.CloseConnection);
          if (!sqlDataReader.HasRows)
          {
            return false;
          }
          return true;
        }

    }
}

ScaleWebTest/Controllers/ScalesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Diagnostics;
using System.Globalization;
using System.Web.Mvc;
using ScaleService;
using System.Linq;
using ScaleWebTest.Properties;

namespace ScaleWebTest.Controllers
{
    public class ScalesController : Controller
    {
        //
        // GET: /Scales/

        public ActionResult Index()
        {
            string host = Session["hostName"] as string;
            if (host == null) return RedirectToAction("Index", "Home");

            try
            {
              //var httpCookie = Request.Cookies["Session"];
              //if (httpCookie == null)
              //{
              //  TempData["error"] = "No se pudo conectar al computador de báscula (" + host + ") especificado.";
              //  return RedirectToAction("Index", "Home");
              //}


              //if (!ValidateCok(httpCookie.Value.ToString(CultureInfo.InvariantCulture)))
              //{
              //  TempData["error"] = "No se pudo conectar al computador de báscula (" + host + ") especificado.";
              //  return RedirectToAction("Index", "Home");
              //}

              Stopwatch queryTime = new Stopwatch();
                ScaleServiceClient client = new ScaleServiceClient(host);

                queryTime.Start();
                IEnumerable<ScaleDTO> scales = client.GetScales();
                queryTime.Stop();
                ViewBag.QueryTime = queryTime.Elapsed.ToString();

                return View(scales);
            }
            catch (Exception)
            {
                TempData["error"] = "No se pudo conectar al computador de báscula (" + host +") especificado.";
                return RedirectToAction("Index", "Home");
            }

        }

        public ActionResult GetWeight(string id)
        {
            string host = Session["hostName"] as string;
            if (host == null) return RedirectToAction("Index", "Home");

            try
            {
                Stopwatch queryTime = new Stopwatch();
                ScaleServiceClient client = new ScaleServiceClient(host);

                queryTime.Start();
                WeightDTO weight = client.GetWeight(id);
                queryTime.Stop();
                if (weight == null) return RedirectToAction("Index");

                ViewBag.QueryTime = queryTime.Elapsed.ToString();
                ViewBag.Id = id;
                return View(weight);
            }
            catch (Exception)
            {
                TempData["error"] = "No se pudo conectar al computador de báscula (" + host + ") especificado.";
                return RedirectToAction("Index", "Home");
            }

        }

        public ActionResult GetWeightJSON(string host, string id)
        {
            Stopwatch stopwatch = new Stopwatch();
            try
            {
                stopwatch.Start();
                ScaleServiceClient client = new ScaleServiceClient(host);
                WeightDTO weight = client.GetWeight(id);
                stopwatch.Stop();
                return Json(weight.Weight + " en " + stopwatch.Elapsed + ".", JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {
                stopwatch.Stop();
                return Json("Sin Conexión en " + stopwatch.Elapsed + ".", JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult Edit(string id)
        {
            string host = Session["hostName"] as string;
            if (host == null) return RedirectToAction("Index", "Home");

            try
            {
                ScaleServiceClient client = new ScaleServiceClient(host);
                ScaleDTO scale = client.GetScales().FirstOrDefault(s => s.Code == id);
                if (scale == null) return RedirectToAction("Index");

                ViewBag.Protocols = client.GetAvailableProtocols();

                return View(scale);
            }
            catch (Exception)
            {
                TempData["error"] = "No se pudo conectar al computador de báscula (" + host + ") especificado.";
                return RedirectToAction("Index", "Home");
            }
            
        }

        [HttpPost]
        public ActionResult Edit(ScaleDTO scale)
        {
            string host = Session["hostName"] as string;
            if (host == null) return RedirectToAction("Index", "Home");

            try
            {
                ScaleServiceClient client = new ScaleServiceClient(host);
                scale.EnabledSpecified = true;
                scale.WeightVariationSpecified = true;
                scale.ComPortInfo.BaudRateSpecified = true;
                scale.ComPortInfo.DataBitsSpecified = true;

                MessageDTO message = client.SetScalesConfiguration(new ScaleDTO[] { scale });

                TempData["info"] = "[" + message.TypeEnum + " - " + message.TransactionNumber + "] " + message.Message;
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                TempData["error"] = "No se pudo conectar al computador de báscula (" + host + ") especificado.";
                return RedirectToAction("Index", "Home");
            }
        }

        public  ActionResult Restart()
        {
            string host = Session["hostName"] as string;
            if (host == null) return RedirectToAction("Index", "Home");

            try
            {
                ScaleServiceClient client = new ScaleServiceClient(host);
                MessageDTO message = client.Restart();

                TempData["info"] = "[" + message.TypeEnum + " - " + message.TransactionNumber + "] " + message.Message;
                return RedirectToAction("Index", "Home");
            }
            catch (Exception)
            {
                TempData["error"] = "No se pudo conectar al computador de báscula (" + host + ") especificado.";
                return RedirectToAction("Index", "Home");
            }
        }
        private bool ValidateCok(string SesCode)
        {
          SqlConnection sqlConnection;
          if (Settings.Default.ExecutionEnvironment.ToLower() == "production")
            sqlConnection = new SqlConnection(Settings.Default.ProductionDbConnectionString);
          else
            sqlConnection = new SqlConnection(Settings.Default.DebugDbConnectionString);
          sqlConnection.Open();
          var SqlQuery = @"select * from adSessions where SesCode='" + SesCode + "'";
          SqlCommand sqlCommand = new SqlCommand(SqlQuery, sqlConnection);
          SqlDataReader sqlDataReader = sqlCommand.ExecuteReader(CommandBehavior.CloseConnection);
          if (!sqlDataReader.HasRows)
          {
            return false;
          }
          return true;
        }
    }
}

ScaleWebTest/Views/Scales/Edit.cshtml
@model ScaleService.ScaleDTO

@{
    ViewBag.Title = "Editar Báscula " + Model.Name;
}

<div class="page-header"><h1>Editar Báscula @Model.Name</h1></div>

<p>@Html.ActionLink("Ir a Lista de Basculas.", "Index")</p>
<p>@Html.ActionLink("Ir a seleccionar Computador de Bascula.", "Index", "Home")</p>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Báscula</legend>
        
        @Html.HiddenFor(model => model.Code)

        <div class="editor-label">
            Código
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.NewCode, new { @Value = Model.Code})
            @Html.ValidationMessageFor(model => model.NewCode)
        </div>
        
        <div class="editor-label">
            Nombre
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>
        
        <div class="editor-label">
            Habilitado
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Enabled)
            @Html.ValidationMessageFor(model => model.Enabled)
        </div>

        <div class="editor-label">
            Modo de Comunicación
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.ComunicationMode, new SelectList(new [] {"Socket", "Serial"}))
            @*@Html.EditorFor(model => model.ComunicationMode)*@
            @Html.ValidationMessageFor(model => model.ComunicationMode)
        </div>

        <div class="editor-label">
            Protocolo de Báscula
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.CurrentProtocol, new SelectList(ViewBag.Protocols))
            @*@Html.EditorFor(model => model.CurrentProtocol)*@
            @Html.ValidationMessageFor(model => model.CurrentProtocol)
        </div>

        <div class="editor-label">
            Variación de Peso
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.WeightVariation)
            @Html.ValidationMessageFor(model => model.WeightVariation)
        </div>
        
        <fieldset>
            <legend>Configuración IP</legend>
            
            <div class="editor-label">
                Nombre del Host
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.SocketInfo.Address)
                @Html.ValidationMessageFor(model => model.SocketInfo.Address)
            </div>
            <div class="editor-label">
                Puerto
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.SocketInfo.Port)
                @Html.ValidationMessageFor(model => model.SocketInfo.Port)
            </div>
        </fieldset>
        
        <fieldset>
            <legend>Configuración Serial</legend>
            
            <div class="editor-label">
                Nombre del Puerto
            </div>
            <div class="editor-field">
                @Html.DropDownListFor(model => model.ComPortInfo.PortName, new SelectList(new [] {"COM1", "COM2", "COM3", "COM4", "COM5", "COM6", "COM7", "COM8"}))
                @Html.ValidationMessageFor(model => model.ComPortInfo.PortName)
            </div>
            <div class="editor-label">
                BaudRate
            </div>
            <div class="editor-field">
                @Html.DropDownListFor(model => model.ComPortInfo.BaudRate, new SelectList(new [] {"300", "600", "1200", "2400", "4800", "9600", "19200", "38400", "57600", "115200"}))
                @Html.ValidationMessageFor(model => model.ComPortInfo.BaudRate)
            </div>
            <div class="editor-label">
                Bits de Datos
            </div>
            <div class="editor-field">
                @Html.DropDownListFor(model => model.ComPortInfo.DataBits, new SelectList(new [] {"7", "8"}))
                @Html.ValidationMessageFor(model => model.ComPortInfo.DataBits)
            </div>
            <div class="editor-label">
                Bits de Parada
            </div>
            <div class="editor-field">
                @Html.DropDownListFor(model => model.ComPortInfo.StopBits, new SelectList(new [] {"0", "1"}))
                @Html.ValidationMessageFor(model => model.ComPortInfo.StopBits)
            </div>
            <div class="editor-label">
                Paridad
            </div>
            <div class="editor-field">
                @Html.DropDownListFor(model => model.ComPortInfo.Parity, new SelectList(new [] {"None", "Even", "Odd"}))
                @Html.ValidationMessageFor(model => model.ComPortInfo.Parity)
            </div>
        </fieldset>
        <p>
            <input type="submit" value="Editar" />
        </p>
    </fieldset>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ScaleWebTest/Views/Scales/GetWeight.cshtml
@model ScaleService.WeightDTO

@{
    ViewBag.Title = "Peso en Báscula " + ViewBag.Id;
}

<div class="page-header"><h2>Peso en Báscula @ViewBag.Id</h2></div>

<p>@Html.ActionLink("Ir a Lista de Básculas.", "Index")</p>
<p>@Html.ActionLink("Ir a seleccionar Computador de Báscula.", "Index", "Home")</p>

<fieldset>
    <legend></legend>
    <div class="display-label">
        Peso
    </div>
    <div class="display-field">
        <h3>@Html.DisplayFor(model => model.Weight)</h3>
    </div>

    <div class="display-label">
        Estado: @Html.DisplayFor(model => model.State)
    </div>

    <div class="display-label">
        Mensaje: [ @Model.Message.TypeEnum - @Model.Message.TransactionNumber ] @Model.Message.Message
    </div>
</fieldset>

<p> </p>
<div class="alert alert-info"><p> Tiempo para completar la consulta: @ViewBag.QueryTime</p></div>

ScaleWebTest/Views/Scales/Index.cshtml
@model IEnumerable<ScaleService.ScaleDTO>

@{
    ViewBag.Title = "Lista de Básculas en " + Session["hostName"];
}

<div class="page-header"><h1>Lista de Basculas en @Session["hostName"]</h1></div>

<p>@Html.ActionLink("Ir a Lista de Protocolos.", "Index", "Protocols")</p>
<p>@Html.ActionLink("Ir a seleccionar Computador de Báscula.", "Index", "Home")</p>
<p>@Html.ActionLink("Reiniciar servicio de basculación.", "Restart", "Scales")</p>


@if(@TempData["info"] != null) { <div class="alert alert-info"><p>@TempData["info"]</p></div> }

<table class="table table-striped">
    <tr>
        <th>
            Código
        </th>
        <th>
            Nombre
        </th>
        <th>
            Habilitado
        </th>
        <th>
            Modo de Comunicación
        </th>
        <th>
            Protocolo de Báscula
        </th>
        <th>
            Variación de Peso
        </th>
        <th>
            Configuración IP
        </th>
        <th>
            Configuración Serial
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Code)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Enabled)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ComunicationMode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CurrentProtocol)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.WeightVariation)
            </td>
            <td>
                @if(item.SocketInfo != null)
                {
                    @: @item.SocketInfo.Address : @item.SocketInfo.Port
                }
            </td>
            <td>
                @{
                    string displayText = "";
                    if(item.ComPortInfo != null)
                    {
                        displayText = item.ComPortInfo.PortName + "  " + item.ComPortInfo.BaudRate + " - " + @item.ComPortInfo.DataBits + " - " + item.ComPortInfo.StopBits + " - " + item.ComPortInfo.Parity;
                    }
                }
                @displayText
            </td>
            <td>
                @Html.ActionLink("Peso", "GetWeight", new { id=item.Code })
                @Html.ActionLink("Editar", "Edit", new { id=item.Code })
            </td>
        </tr>
    }
</table>

<p> </p>
<div class="alert alert-info"><p> Tiempo para completar la consulta: @ViewBag.QueryTime</p></div>